// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnamsaxszqdymtuanwnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuYW1zYXhzenFkeW10dWFud25sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxNjYzMzQsImV4cCI6MjA1Mzc0MjMzNH0.K1fsHzWx-EBIUPX44BpNxQ83siNfHY0kOUiD69gbtAI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);